### ISSUE TITLE
v 3.1.6 Initialisation error

### ISSUE THREAD

**Issue by gNetLabs** [sendinblue/APIv3-nodejs-library#22]
while using the new version 3.1.6

the module can not be initialized.

Cannot find module './model/RequestSmsRecipientExport' at require (internal/module.js:20:19) at exports.ApiClient (........./sib-api-v3-sdk/src/index.js:23:4527) at Object.<anonymous> (........./sib-api-v3-sdk/src/index.js:25:2)

**Comment by Kira2** [comment]
Hi,

Got this error message too when trying to deploy my server on an Elastic Beanstalk‎ environment on AWS.

node version : v6.11.1
npm version : 3.10.10

It works with the previous version 3.1.5 of API.
Thank you.

**Comment by ekta-slit** [comment]
@gNetLabs Thanks for reporting the issue, we will fix and update soon.

**Comment by ekta-slit** [comment]
Hello,

We have recently done some changes in spec and missed to change major version, apologies for that.
We have re-updated our releases.
You can now update to any version of `3.1.x` without any issue.
Our version is `4.0.x` for latest features.

Thanks
